# Generated by Django 5.0 on 2023-12-10 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_diverdetails_alter_ridedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedetails',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.diverdetails'),
        ),
    ]
