# Generated by Django 5.0 on 2023-12-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_ridedetails_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiverDetails',
            new_name='DriverDetails',
        ),
        migrations.AlterField(
            model_name='rideuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('driver', 'Driver'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
